### ISSUE TITLE
Received Mockery_0_Illuminate_Cache_CacheManager::driver(), but no expectations were specified

### ISSUE THREAD

**Issue by QuentinLuc** [renoki-co/laravel-eloquent-query-cache#205]
Hey!  

I've got a basic integration test in which I want to mock `Cache::remember` - Facade Cache -  which I do like this:
```
Cache::shouldReceive('remember')
            ->once()
            ->with($cache_key, \Mockery::any(), \Closure::class)
            ->andReturn(null);

$response = $this->actingAs($user)->withHeaders(TestUtils::getAuthorizationHeader())->get($url);

$response->assertStatus(500);
```

However, I get the following error message:
```
[2023-10-03 11:33:29] testing.ERROR: Received Mockery_0_Illuminate_Cache_CacheManager::driver(), but no expectations were specified {"userId":210,"exception":"[object] (Mockery\\Exception\\BadMethodCallException(code: 0): Received Mockery_0_Illuminate_Cache_CacheManager::driver(), but no expectations were specified at /test_project/vendor/mockery/mockery/library/Mockery/Loader/EvalLoader.php(34) : eval()'d code:933)
[stacktrace]
#0 /test_project/vendor/mockery/mockery/library/Mockery/Loader/EvalLoader.php(34) : eval()'d code(996): Mockery_0_Illuminate_Cache_CacheManager->_mockery_handleMethodCall('driver', Array)
#1 /test_project/vendor/rennokki/laravel-eloquent-query-cache/src/Traits/QueryCacheModule.php(338): Mockery_0_Illuminate_Cache_CacheManager->driver(NULL)
#2 /test_project/vendor/rennokki/laravel-eloquent-query-cache/src/Traits/QueryCacheModule.php(348): Rennokki\\QueryCache\\Query\\Builder->getCacheDriver()
#3 /test_project/vendor/rennokki/laravel-eloquent-query-cache/src/Traits/QueryCacheModule.php(79): Rennokki\\QueryCache\\Query\\Builder->getCache()
#4 /test_project/vendor/rennokki/laravel-eloquent-query-cache/src/Query/Builder.php(21): Rennokki\\QueryCache\\Query\\Builder->getFromQueryCache('get', Array)
#5 /test_project/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(710): Rennokki\\QueryCache\\Query\\Builder->get(Array)
#6 /test_project/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(694): Illuminate\\Database\\Eloquent\\Builder->getModels(Array)
#7 /test_project/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(296): Illuminate\\Database\\Eloquent\\Builder->get(Array)
#8 /test_project/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2042): Illuminate\\Database\\Eloquent\\Builder->first()
#9 /test_project/vendor/laravel/framework/src/Illuminate/Routing/ImplicitRouteBinding.php(61): Illuminate\\Database\\Eloquent\\Model->resolveRouteBinding('122', NULL)
#10 /test_project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(947): Illuminate\\Routing\\ImplicitRouteBinding::resolveForRoute(Object(Illuminate\\Foundation\\Application), Object(Illuminate\\Routing\\Route))
#11 /test_project/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Router->substituteImplicitBindings(Object(Illuminate\\Routing\\Route))
#12 /test_project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#13 /test_project/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#14 /test_project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'api')
#15 /test_project/app/Http/Middleware/GzipEncodeResponse.php(13): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#16 /test_project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\GzipEncodeResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#17 /test_project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#18 /test_project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(797): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#19 /test_project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(776): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#20 /test_project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(740): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#21 /test_project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(729): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#22 /test_project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#23 /test_project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#24 /test_project/vendor/livewire/livewire/src/DisableBrowserCache.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /test_project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Livewire\\DisableBrowserCache->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /test_project/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(59): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /test_project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /test_project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /test_project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /test_project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 /test_project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /test_project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 /test_project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 /test_project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 /test_project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 /test_project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 /test_project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 /test_project/vendor/fruitcake/laravel-cors/src/HandleCors.php(52): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /test_project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 /test_project/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 /test_project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 /test_project/vendor/beyondcode/laravel-server-timing/src/Middleware/ServerTimingMiddleware.php(36): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 /test_project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): BeyondCode\\ServerTiming\\Middleware\\ServerTimingMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 /test_project/app/Http/Middleware/RequestUniqueIdMiddleware.php(16): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 /test_project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\RequestUniqueIdMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /test_project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /test_project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#48 /test_project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#49 /test_project/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php(556): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#50 /test_project/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php(324): Illuminate\\Foundation\\Testing\\TestCase->call('GET', 'v3/farm-seasons...', Array, Array, Array, Array)
#51 /test_project/tests/Feature/v3/FarmSeasonFieldController/WhenGettingFieldSnapshotTest.php(80): Illuminate\\Foundation\\Testing\\TestCase->get('v3/farm-seasons...')
#52 /test_project/vendor/phpunit/phpunit/src/Framework/TestCase.php(1608): Tests\\Feature\\v3\\FarmSeasonOperationController\\WhenGettingFieldSnapshotTest->test_get_should_http_500_error_when_image_not_generated()
#53 /test_project/vendor/phpunit/phpunit/src/Framework/TestCase.php(1214): PHPUnit\\Framework\\TestCase->runTest()
#54 /test_project/vendor/phpunit/phpunit/src/Framework/TestResult.php(728): PHPUnit\\Framework\\TestCase->runBare()
#55 /test_project/vendor/phpunit/phpunit/src/Framework/TestCase.php(964): PHPUnit\\Framework\\TestResult->run(Object(Tests\\Feature\\v3\\FarmSeasonOperationController\\WhenGettingFieldSnapshotTest))
#56 /test_project/vendor/phpunit/phpunit/src/Framework/TestSuite.php(684): PHPUnit\\Framework\\TestCase->run(Object(PHPUnit\\Framework\\TestResult))
#57 /test_project/vendor/phpunit/phpunit/src/Framework/TestSuite.php(684): PHPUnit\\Framework\\TestSuite->run(Object(PHPUnit\\Framework\\TestResult))
#58 /test_project/vendor/phpunit/phpunit/src/Framework/TestSuite.php(684): PHPUnit\\Framework\\TestSuite->run(Object(PHPUnit\\Framework\\TestResult))
#59 /test_project/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(651): PHPUnit\\Framework\\TestSuite->run(Object(PHPUnit\\Framework\\TestResult))
#60 /test_project/vendor/phpunit/phpunit/src/TextUI/Command.php(144): PHPUnit\\TextUI\\TestRunner->run(Object(PHPUnit\\Framework\\TestSuite), Array, Array, true)
#61 /test_project/vendor/phpunit/phpunit/src/TextUI/Command.php(97): PHPUnit\\TextUI\\Command->run(Array, true)
#62 /test_project/vendor/phpunit/phpunit/phpunit(107): PHPUnit\\TextUI\\Command::main()
#63 {main}
"} 

```

Do you know how I could fix this?

Thanks, 

Quentin.

**Comment by rennokki** [comment]
Use [partial mocking](https://laravel.com/docs/9.x/mocking#:~:text=%7D)%3B-,You%20may%20use%20the,methods%20that%20are%20not%20mocked%20will%20be%20executed%20normally%20when%20called%3A,-use%20App%5C)
